name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [city-service, ai-service, economy-service, user-service]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: |
        cd ai-city-simulator-backend/services/${{ matrix.service }}
        npm ci
    - name: Run tests
      run: |
        cd ai-city-simulator-backend/services/${{ matrix.service }}
        npm test

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [city-service, ai-service, economy-service, user-service]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: |
        cd ai-city-simulator-backend/services/${{ matrix.service }}
        npm ci
    - name: Run ESLint
      run: |
        cd ai-city-simulator-backend/services/${{ matrix.service }}
        npm run lint

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [city-service, ai-service, economy-service, user-service]

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        cd ai-city-simulator-backend/services/${{ matrix.service }}
        docker build -t ${{ matrix.service }}:${{ github.sha }} .

  deploy-staging:
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure Heroku CLI
      run: |
        echo "Configuring Heroku CLI"
        heroku container:login
    - name: Deploy to Heroku staging
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:push web -a ai-city-simulator-staging
        heroku container:release web -a ai-city-simulator-staging

  deploy-production:
    needs: [build, deploy-staging]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure Heroku CLI
      run: |
        echo "Configuring Heroku CLI"
        heroku container:login
    - name: Deploy to Heroku production
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:push web -a ai-city-simulator
        heroku container:release web -a ai-city-simulator
    - name: Push changes to main branch
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "Update files after deployment"
        git push origin main
